sudo: false
     
language: node_js
node_js:
    - "4.5.0"
         
before_install:
    - curl https://install.meteor.com | /bin/sh
    - export PATH="$HOME/.meteor:$PATH"
                 
script:
    - meteor --once test-packages ./ --driver-package practicalmeteor:mocha
